<?xml version="1.0"?>
<package format="2">
  <name>tianracer</name>
  <version>1.0.0</version>
  <description>Tianracer is a meta-package for tianbot racecar</description>
  <maintainer email="tianb03@hotmail.com">Tian Bo</maintainer>
  <license>GPLv3</license>
  <buildtool_depend>catkin</buildtool_depend>
  <export>
    <metapackage />
  </export>
</package>
